---
config:
  matomo:
    enabled: true
    auth:
      apiToken: "a-test-api-tokeen"
    baseUrl: "my-matomo.com"
    siteId: "REDACTED"
  mercure:
    enabled: true
    auth:
      jwtSecret: "a-test-jwt-secret"
    publicHubUrl: "my-public-mercure-hub.com"
    internalHubUrl: "my-internal-mercure-hub.com"
