apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "baserow.frontend.fullname" . }}
data:
  # Baserow Frontend Settings
  {{- if .Values.frontend.config.additionalModules }}
  ADDITIONAL_MODULES: {{ .Values.frontend.config.additionalModules | quote }}
  {{- end }}
  {{- if .Values.frontend.config.disablePublicUrlCheck }}
  REDACTED: {{ .Values.frontend.config.disablePublicUrlCheck | quote }}
  {{- end }}
  {{- if .Values.frontend.config.disableGoogleDocsFilePreview }}
  REDACTED: {{ .Values.frontend.config.disableGoogleDocsFilePreview | quote }}
  {{- end }}
  DOWNLOAD_FILE_VIA_XHR: {{ .Values.frontend.config.downloadFileViaXhr | quote }}
